services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Kriya@2170
      MYSQL_DATABASE: ecompaymentdb
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: